config {
  type: "table", // Creates a view in BigQuery. Try changing to "table" instead.
  name: "source",
  description: "description of the table",
  tags: ["favourite","least_liked"],
}

SELECT
  "apples" AS fruit,
  3 AS count
UNION ALL
SELECT
  "oranges" AS fruit,
  5 AS count
UNION ALL
SELECT
  "pears" AS fruit,
  1 AS count
UNION ALL
SELECT
  "bananas" AS fruit,
  0 AS count
UNION ALL
SELECT
  "kiwi" AS fruit,
  10 AS count

